server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/springboot_demo
    username: root
    password: MHx4hA5k
  mvc:
  
    view:
      suffix: .html
      prefix: /
  
  #微信配置
wx:        
    #微信公众号或者小程序等的appid
    appId: wxa004c50b7a3a7a1d
    #应用密钥
    appSecret: 3a1c89c8bbfb73d00995905c2e852a5a
    #微信支付商户号
    merchantId: 1680044857
    #微信支付商户密钥
    mchKey: WRFGZXCVBnilseeryut918678001yufh
    #商户证书目录
    keyPath: D:\xiaoChengXuAPIInstall\WXCertUtil\cert\1680044857_20240707_cert
    #商户API私钥路径 部署到centos后 /etc/wx-pay/apiclient_cert.pem
    privateKeyPath: D:\xiaoChengXuAPIInstall\WXCertUtil\cert\1680044857_20240707_cert\apiclient_cert.pem
    #商户API密钥证书路径 部署到centos后 /etc/wx-pay/apiclient_key.pem
    wechatPayCertificatePath: D:\xiaoChengXuAPIInstall\WXCertUtil\cert\1680044857_20240707_cert\apiclient_key.pem
    #商户证书序列号
    merchantSerialNumber: 68E9D4BC10D46D026CBF0CBBE18EC957C2BA4904
    #商户APIV3密钥
    apiV3Key: QSERFGtyjopuiycERHY4765RThFTY001

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
